comment: false
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

# When modifying this file, please validate using
# curl -X POST --data-binary @codecov.yml https://codecov.io/validate
